spring:
  application:
    name:
      - ApiGateway
  cloud:
    gateway.server.webmvc:
      routes:
        - id: file-analysis-route
          uri: http://localhost:8080
          predicates:
            - Path=/file-analysis/**
          filters:
            - StripPrefix=1
        - id: file-storing-route
          uri: http://localhost:8081
          predicates:
            - Path=/file-storing/**
          filters:
            - StripPrefix=1
server:
  port:
    8079